apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
  labels:
    role: frontend
    app: front
spec:
  type: ClusterIP
  loadBalancerIP: 10.240.4.4
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    role: frontend
    app: front