apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-baseline-settings
  namespace: flux-system
spec:
  interval: 1m
  path: ./IaC/terraform/cluster-baseline-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
