# Creates Ingress Certificate and Pushes to Key Vault

name: Create and Push Ingress Certs to AKV

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'A GitHub Environment to pull action secrets from'
        required: true
        type: environment
      DOMAIN:
        description: 'The domain name to use for the certs (ie: contoso.com)'
        required: true
        default: 'contoso.com'
        type: string
      CN:
        description: 'The CN to be used along with the Domain (ie: bicycle will result in fqdn of bycicle.contoso.com)'
        required: true
        default: 'bicycle'
        type: string
      AKVNAME:
        description: 'The Name of the AKV resource'
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  event_sha: +refs/pull/${{ github.event.issue.number }}/merge

permissions:
      id-token: write
      contents: read

jobs:
  App_Init:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      DOMAIN: "${{ inputs.DOMAIN}}"
      CN: "${{ inputs.CN }}"
      AKVNAME: "${{ inputs.AKVNAME}}"

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Job parameter inspection
        run: |
          echo "ENVIRONMENT is ${{ inputs.ENVIRONMENT }}"
          echo "DOMAIN is ${{ inputs.DOMAIN }}"
          echo "CN is ${{ inputs.CN }}"
          echo "AKV name is ${{ inputs.AKVNAME }}"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate Certs
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -out appgw.crt -keyout appgw.key -subj "/CN=${{ inputs.CN }}.${{ inputs.DOMAIN }}/O=Default" -addext "subjectAltName = DNS:${{ inputs.CN }}.${{ inputs.DOMAIN }}" -addext "keyUsage = digitalSignature" -addext "extendedKeyUsage = serverAuth"
          openssl pkcs12 -export -out appgw.pfx -in appgw.crt -inkey appgw.key -passout pass:
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -out traefik-ingress-internal-aks-ingress-tls.crt -keyout traefik-ingress-internal-aks-ingress-tls.key -subj "/CN=*.aks-ingress.${{ inputs.DOMAIN }}/O=Contoso AKS Ingress"
          cat traefik-ingress-internal-aks-ingress-tls.crt traefik-ingress-internal-aks-ingress-tls.key > traefik-ingress-internal-aks-ingress-tls.pem
          AKS_INGRESS_CONTROLLER_CERTIFICATE=$(cat traefik-ingress-internal-aks-ingress-tls.crt | base64 | tr -d '\n')
          echo "AKS_INGRESS_CONTROLLER_CERTIFICATE=$AKS_INGRESS_CONTROLLER_CERTIFICATE" >> $GITHUB_ENV
          echo "AKS_INGRESS_CONTROLLER_CERTIFICATE=$AKS_INGRESS_CONTROLLER_CERTIFICATE"

      - name: Create role assignment for upload
        run: |
          ASSIGNEE_OBJ_ID=$(az ad sp show --id ${{ secrets.AZURE_CLIENT_ID }} --query id -o tsv)
          echo "ASSIGNEE_OBJ_ID=$ASSIGNEE_OBJ_ID" >> $GITHUB_ENV
          AKV_RESOURCE_ID=$(az keyvault show -n ${{ inputs.AKVNAME }} --query id -o tsv)
          echo "AKV_RESOURCE_ID=$AKV_RESOURCE_ID" >> $GITHUB_ENV
          TEMP_ROLEASSIGNMENT_TO_UPLOAD_CERT=$(az role assignment create --role a4417e6f-fecd-4de8-b567-7b0420556985 --assignee-principal-type serviceprincipal --assignee-object-id $ASSIGNEE_OBJ_ID --scope $AKV_RESOURCE_ID | jq '.id' )
          echo "TEMP_ROLEASSIGNMENT_TO_UPLOAD_CERT=$TEMP_ROLEASSIGNMENT_TO_UPLOAD_CERT" >> $GITHUB_ENV
          # put a sleep step

      - name: Add Network Rule
        run: |
          CURRENT_IP_ADDRESS=$(curl -s -4 https://ifconfig.io)
          echo "CURRENT_IP_ADDRESS=$CURRENT_IP_ADDRESS" >> $GITHUB_ENV
          az keyvault network-rule add -n ${{ inputs.AKVNAME }} --ip-address ${CURRENT_IP_ADDRESS}

      - name: Import Cert
        run: |
          az keyvault certificate import -f traefik-ingress-internal-aks-ingress-tls.pem -n traefik-ingress-internal-aks-ingress-tls --vault-name ${{ inputs.AKVNAME }}


      - name: Remove Network Rule
        run: |
          az keyvault network-rule remove -n ${{ inputs.AKVNAME }} --ip-address "${{ env.CURRENT_IP_ADDRESS }}/32"

      - name: Remove role assignment
        run: |
          az role assignment delete --ids ${{ env.TEMP_ROLEASSIGNMENT_TO_UPLOAD_CERT }}
          